/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { JSONValue } from "@metrichor/jmespath/dist/types/typings";
export namespace Components {
    interface JmespathEdit {
        "expression": string;
        "json": JSONValue;
        "library": string;
    }
    interface JmespathEditDemo {
    }
}
declare global {
    interface HTMLJmespathEditElement extends Components.JmespathEdit, HTMLStencilElement {
    }
    var HTMLJmespathEditElement: {
        prototype: HTMLJmespathEditElement;
        new (): HTMLJmespathEditElement;
    };
    interface HTMLJmespathEditDemoElement extends Components.JmespathEditDemo, HTMLStencilElement {
    }
    var HTMLJmespathEditDemoElement: {
        prototype: HTMLJmespathEditDemoElement;
        new (): HTMLJmespathEditDemoElement;
    };
    interface HTMLElementTagNameMap {
        "jmespath-edit": HTMLJmespathEditElement;
        "jmespath-edit-demo": HTMLJmespathEditDemoElement;
    }
}
declare namespace LocalJSX {
    interface JmespathEdit {
        "expression"?: string;
        "json"?: JSONValue;
        "library"?: string;
    }
    interface JmespathEditDemo {
    }
    interface IntrinsicElements {
        "jmespath-edit": JmespathEdit;
        "jmespath-edit-demo": JmespathEditDemo;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "jmespath-edit": LocalJSX.JmespathEdit & JSXBase.HTMLAttributes<HTMLJmespathEditElement>;
            "jmespath-edit-demo": LocalJSX.JmespathEditDemo & JSXBase.HTMLAttributes<HTMLJmespathEditDemoElement>;
        }
    }
}
