/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface JmespathPreview {
    }
}
declare global {
    interface HTMLJmespathPreviewElement extends Components.JmespathPreview, HTMLStencilElement {
    }
    var HTMLJmespathPreviewElement: {
        prototype: HTMLJmespathPreviewElement;
        new (): HTMLJmespathPreviewElement;
    };
    interface HTMLElementTagNameMap {
        "jmespath-preview": HTMLJmespathPreviewElement;
    }
}
declare namespace LocalJSX {
    interface JmespathPreview {
    }
    interface IntrinsicElements {
        "jmespath-preview": JmespathPreview;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "jmespath-preview": LocalJSX.JmespathPreview & JSXBase.HTMLAttributes<HTMLJmespathPreviewElement>;
        }
    }
}
